name: skills_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - asttokens
  - blas
  - blosc
  - bottleneck
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - gettext
  - glib
  - glib-tools
  - gst-plugins-base
  - gstreamer
  - hdf5
  - icu
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - krb5
  - libclang
  - libcurl
  - libcxx
  - libedit
  - libev
  - libexpat
  - libffi
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libllvm12
  - libnghttp2
  - libopenblas
  - libpng
  - libpq
  - libsodium
  - libsqlite
  - libssh2
  - libzlib
  - llvm-openmp
  - lz4-c
  - lzo
  - matplotlib-inline
  - ncurses
  - nest-asyncio
  - nspr
  - nss
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandas
  - parso
  - pcre2
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - ply
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - py-cpuinfo
  - pygments
  - pyqt
  - pyqt5-sip
  - pytables
  - python
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - pyzmq
  - qt-main
  - qtpy
  - readline
  - setuptools
  - sip
  - six
  - snappy
  - sqlite
  - stack_data
  - tk
  - tomli
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - vitables
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - zlib-ng
  - zstd
  - pip:
      - h5py
      - msgpack
      - natsort
      - opencv-python
      - pillo
